services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony_network
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: symfony_web
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge